source 'https://rubygems.org'

gem 'concurrent-ruby-edge'
gem 'faye-websocket'
gem 'mysql2'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'newrelic_rpm'
gem 'stackprof'
gem 'pry'

group :test do
  gem 'rspec'
end
